// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV5sApSTmG5LPvJ0DsFcaWQRRp7jJ98gQ',
    appId: '1:452156666399:web:07435eb6252703962fdb2a',
    messagingSenderId: '452156666399',
    projectId: 'flutter-chat18',
    authDomain: 'flutter-chat18.firebaseapp.com',
    storageBucket: 'flutter-chat18.appspot.com',
    measurementId: 'G-VZ5293F603',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB4zFKyN5h-c0gfwG1tQD80xYpJM5PygQ',
    appId: '1:452156666399:android:feb7478dca638a1e2fdb2a',
    messagingSenderId: '452156666399',
    projectId: 'flutter-chat18',
    storageBucket: 'flutter-chat18.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAmspXiM6HQeMcQMLb6PFOOTi1vqBcl9U',
    appId: '1:452156666399:ios:c2d6e55905833ce72fdb2a',
    messagingSenderId: '452156666399',
    projectId: 'flutter-chat18',
    storageBucket: 'flutter-chat18.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAmspXiM6HQeMcQMLb6PFOOTi1vqBcl9U',
    appId: '1:452156666399:ios:06e33795f2d987732fdb2a',
    messagingSenderId: '452156666399',
    projectId: 'flutter-chat18',
    storageBucket: 'flutter-chat18.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
